[alpha]
name = "fruity_mf1.5"
prior = "Normal"
prior_args = [2.60, 0.0]

[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]

[zeta_cc]
name = "linear"
y_shift = -1
prior = "Normal"
prior_args = [0.0, 1.0]

[A_cc]
name = "quadratic"
prior = "Normal"
prior_args = [0.0, 4.0]
