[alpha]
name = "monash"
prior = "Normal"
prior_args = [1.0, 1.0]

[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]

[zeta_cc]
name = "linear"
prior = "Normal"
prior_args = [0.0, 2.0]
y_shift = -1

[A_cc]
name = "quadratic"
prior = "Normal"
prior_args = [0.0, 4.0]
