datafile = "~/surp/carbon_paper/data_analysis/gso_dwarfs.csv"
mg_h_bins = [-0.5, -0.3, -0.1, 0.1, 0.3, 0.5]
mg_fe_bins = [-0.2, 0.0, 0.2, 0.4]

mg_fe_shift = -0.2

[alpha]
name = "fiducial"
C_MG = "AG_MG"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "fiducial"
C_MG = "CD_MG"

prior = "Normal"
prior_args = [2.0, 1.0]




[zeta_cc]
name = "fiducial"
C_MG = "IN_MG"
y_shift = -2
prior = "Normal"
prior_args = [0.0, 2.0]



[A_cc]
name = "fiducial"
prior = "Normal"
prior_args = [0.0, 4.0]
C_MG = "SN_MG"
