[alpha]
name = "fruity_mf0.7"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]



[zeta_cc]
name = "linlinear"
prior = "Normal"
prior_args = [0.0, 2.0]
y_shift = -0.4342944819032518


[sigma_int]
prior = "Normal"
prior_args = [0.0, 0.0]
