[alpha]
name = "fruity"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]




[A_cc]
name = "quadratic_m0.5"
prior = "Normal"
prior_args = [0.0, 4.0]
