[alpha]
name = "fruity"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]



[zeta_cc]
name = "linear_m0.7"
y_shift = -0.7
prior = "TruncNormal"
prior_args = [0.0, 2.0, 0.0, inf]


[A_cc]
name = "quadratic_m0.7"
prior = "Normal"
y_shift = -0.49
prior_args = [0.0, 4.0]
