[alpha]
name = "perturbations/fruity"
prior = "TruncNormal"
prior_args = [1.0, 1.0, 0.0, inf]


[y0_cc]
name = "perturbations/constant"
prior = "TruncNormal"
prior_args = [2.0, 1.0, 0.0, inf]




[zeta_cc]
name = "perturbations/linear"
prior = "TruncNormal"
prior_args = [0.0, 2.0, 0.0, inf]
y0 = 1e-3


