[alpha]
name = "perturbations/fruity_mf0.7"
prior = "Normal"
prior_args = [2.34, 0.0]


[y0_cc]
name = "perturbations/constant"
prior = "Normal"
prior_args = [2.0, 1.0]




[zeta_cc]
name = "perturbations/linear"
prior = "Normal"
prior_args = [0.0, 2.0]
y0 = 1e-3


