# bin width of 0.04*2 = 0.08
mg_h_bins = [-0.5 , -0.42, -0.34, -0.26, -0.18, -0.1 , -0.02,  0.06,  0.14, 0.22,  0.3 ,  0.38,  0.46]
mg_fe_bins = [-0.1 , -0.02,  0.06,  0.14,  0.22,  0.3 ,  0.38]

[alpha]
name = "perturbations/fruity"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "perturbations/constant"
prior = "Normal"
prior_args = [2.0, 1.0]




[zeta_cc]
name = "perturbations/linear"
prior = "Normal"
prior_args = [0.0, 2.0]
y0 = 1e-3


