
[alpha]
name = "fruity"
prior = "Normal"
prior_args = [1.0, 1.0]

[y0_cc]
name = "const_cc"
prior = "Normal"
prior_args = [2.0, 1.0]

[zeta_cc]
name = "linear"
y_shift = -1
prior = "Normal"
prior_args = [0.0, 2.0]

[sigma_int]
prior = "Normal"
prior_args = [0.0, 0.0]
