[alpha]
name = "hydrodisk"
C_MG = "AG_MG"
prior = "Normal"
prior_args = [1.0, 1.0]


[y0_cc]
name = "hydrodisk"
C_MG = "CD_MG"

prior = "Normal"
prior_args = [2.0, 1.0]




[zeta_cc]
name = "hydrodisk"
C_MG = "IN_MG"
y_shift = -1
prior = "Normal"
prior_args = [0.0, 2.0]



[A_cc]
name = "hydrodisk"
prior = "Normal"
prior_args = [0.0, 4.0]
C_MG = "SN_MG"
